### ISSUE TITLE
Practica de Hilos en Consola

### ISSUE THREAD

**Issue by JoseABCruz** [SistemasTecTlaxiaco/practica-de-hilos-JoseABCruz#2]
[Practica de Hilos en Consola.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-JoseABCruz/files/8421049/Practica.de.Hilos.en.Consola.pdf)

**Comment by JudithReynaCS** [comment]
CALIFICACION:18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
